name: Ruby

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        gemfile:
          - 'Gemfile.dry-config-0.12'
          - 'Gemfile.dry-config-0.14'
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RUBY_VERSION: ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run linter
      run: bundle exec rubocop
    - name: Run test
      run: bundle exec rspec
